name: qof
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - bzip2
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - readline
  - sqlite
  - tk
  - xz
  - zlib
  - tzdata
  - scipy
  - matplotlib
  - networkx
  - pip:
      - annotated-types==0.7.0
      - authlib==1.4.1
      - blinker==1.9.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cryptography==44.0.1
      - cycler==0.12.1
      - deprecated==1.2.18
      - diskcache==5.6.3
      - fasteners==0.19
      - fonttools==4.56.0
      - homebase==1.0.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - numpy==1.26.4
      - orjson==3.10.15
      - packaging==24.2
      - pillow==11.1.0
      - plucky==0.4.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - six==1.17.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0
      - flask==3.1.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - opencv-python==4.11.0.86
      - dimod==0.12.18
      - dwave-cloud-client==0.13.2
      - dwave-gate==0.3.3
      - dwave-hybrid==0.6.13
      - dwave-inspector==0.5.2
      - dwave-neal==0.6.0
      - dwave-networkx==0.8.16
      - dwave-ocean-sdk==8.1.0
      - dwave-optimization==0.4.2
      - dwave-preprocessing==0.6.7
      - dwave-samplers==1.4.0
      - dwave-system==1.28.0
      - dwavebinarycsp==0.3.1
      - minorminer==0.2.16
      - penaltymodel==1.2.0
      - pyqubo==1.5.0
      - flow-vis==0.1
